services:
 nginx:
  image: nginx:alpine
  restart: unless-stopped
  tty: true
  ports:
   - '80:80'
  volumes: 
   - ./src:/var/www/html
   - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  depends_on: 
   - php
   - mysql
  networks: 
   - wp

 mysql:
  platform: linux/amd64
  image: mysql:latest
  restart: unless-stopped
  tty: true
  ports:
   - '3306:3306'
  volumes:
   - ./docker/mysql:/var/lib/mysql
  environment:
   MYSQL_DATABASE: 'wordpress'
   MYSQL_USER: '${MYSQL_USER}'
   MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
   MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
  networks:
   - wp

 php:
  restart: unless-stopped
  tty: true
  build:
   context: ./docker/php
   dockerfile: Dockerfile
  environment:
   WORDPRESS_DB_HOST: 'mysql:3306'
   WORDPRESS_DB_USER: '${MYSQL_USER}'
   WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
   WORDPRESS_DB_NAME: 'wordpress'
  volumes:
   - ./src:/var/www/html
  depends_on:
   - mysql
  networks:
   - wp

 redis:
  image: redis:alpine
  restart: unless-stopped
  ports:
    - '6379:6379'
  networks:
    - wp

networks:
 wp:
  driver: bridge
